In [1]:
import pandas as pd

# Update with the absolute or relative file path
data_path = 'C:/Users/user/Desktop/DA/data/features.csv'

# Load the dataset
df = pd.read_csv(data_path)

# Display the first few rows
print("Dataset Preview:")
print(df.head())

# Overview of the dataset
print("\nDataset Info:")
print(df.info())

# Check for missing values
print("\nMissing Values Before Cleaning:")
print(df.isnull().sum())

# Fill missing values
df['CPI'] = df['CPI'].fillna(df['CPI'].mean())  # Fill CPI missing values with the mean
df['Unemployment'] = df['Unemployment'].fillna(df['Unemployment'].mean())  # Fill Unemployment missing values with the mean

# Fill markdown columns with 0
markdown_cols = ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']
for col in markdown_cols:
    df[col] = df[col].fillna(0)

# Check for remaining missing values
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

# Statistical summary of numerical columns
print("\nStatistical Summary:")
print(df.describe())

# Validate data types
print("\nData Types:")
print(df.dtypes)

Dataset Preview:
   Store        Date  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0      1  2010-02-05        42.31       2.572        NaN        NaN
1      1  2010-02-12        38.51       2.548        NaN        NaN
2      1  2010-02-19        39.93       2.514        NaN        NaN
3      1  2010-02-26        46.63       2.561        NaN        NaN
4      1  2010-03-05        46.50       2.625        NaN        NaN

   MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday
0        NaN        NaN        NaN  211.096358         8.106      False
1        NaN        NaN        NaN  211.242170         8.106       True
2        NaN        NaN        NaN  211.289143         8.106      False
3        NaN        NaN        NaN  211.319643         8.106      False
4        NaN        NaN        NaN  211.350143         8.106      False

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   object
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), object(1)
memory usage: 712.0+ KB
None

Missing Values Before Cleaning:
Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

Missing Values After Cleaning:
Store           0
Date            0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday       0
dtype: int64

Statistical Summary:
             Store  Temperature   Fuel_Price      MarkDown1      MarkDown2  \
count  8190.000000  8190.000000  8190.000000    8190.000000    8190.000000
mean     23.000000    59.356198     3.405992    3462.090725    1206.981664
std      12.987966    18.678607     0.431337    7388.916286    5495.556015
min       1.000000    -7.290000     2.472000   -2781.450000    -265.760000
25%      12.000000    45.902500     3.041000       0.000000       0.000000
50%      23.000000    60.710000     3.513000       0.000000       0.000000
75%      34.000000    73.880000     3.743000    4639.585000      98.590000
max      45.000000   101.950000     4.468000  103184.980000  104519.540000

           MarkDown3     MarkDown4      MarkDown5          CPI  Unemployment
count    8190.000000   8190.000000    8190.000000  8190.000000   8190.000000
mean      776.464219   1392.763115    2043.403725   172.460809      7.826821
std      7539.953758   4707.111488    9431.223215    38.292649      1.808963
min      -179.260000      0.000000    -185.170000   126.064000      3.684000
25%         0.000000      0.000000       0.000000   132.653774      6.833000
50%         0.000000      0.000000       0.000000   172.460809      7.826821
75%        24.220000    774.692500    2680.295000   212.766994      8.519000
max    149483.310000  67474.850000  771448.100000   228.976456     14.313000

Data Types:
Store             int64
Date             object
Temperature     float64
Fuel_Price      float64
MarkDown1       float64
MarkDown2       float64
MarkDown3       float64
MarkDown4       float64
MarkDown5       float64
CPI             float64
Unemployment    float64
IsHoliday          bool
dtype: object